<a href="https://colab.research.google.com/github/youssef1061/RAG-ecommerce-support-chatbot/blob/main/NLP_Final_Task_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
!pip -q install datasets sentence-transformers faiss-cpu transformers accelerate scikit-learn pandas matplotlib seaborn

In [34]:
!pip -q install -U datasets huggingface_hub

In [35]:
!pip -q install -U faiss-cpu

## **Libraries and Configuration**

In [36]:
import re
import random
import unicodedata
from collections import Counter

import faiss
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from datasets import load_dataset
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score
from sklearn.pipeline import Pipeline
from transformers import pipeline

SEED = 42
random.seed(SEED)
np.random.seed(SEED)


def clean_text(text):
    if text is None:
        return ""
    text = unicodedata.normalize("NFKC", str(text))
    return re.sub(r"\s+", " ", text).strip()


def safe_confidence(model, texts):
    probabilities = model.predict_proba(texts)
    return probabilities.max(axis=1)

## **Module 1: language detection**

In [37]:
language_ds = load_dataset("papluca/language-identification")
print(language_ds)
print(language_ds["train"].column_names)
print(language_ds["train"][0])

# Small balanced subset so it trains before the deadline.
train_df = language_ds["train"].to_pandas()
valid_df = language_ds["validation"].to_pandas()
test_df = language_ds["test"].to_pandas()

SAMPLES_PER_LANGUAGE = 800
train_small = (
    train_df.groupby("labels", group_keys=False)
    .apply(lambda group: group.sample(n=min(SAMPLES_PER_LANGUAGE, len(group)), random_state=SEED))
    .sample(frac=1, random_state=SEED)
    .reset_index(drop=True)
)

language_model = Pipeline([
    ("tfidf", TfidfVectorizer(analyzer="char_wb", ngram_range=(3, 5), min_df=2, max_features=100_000)),
    ("clf", LogisticRegression(max_iter=500, n_jobs=-1, random_state=SEED))
])

language_model.fit(train_small["text"].map(clean_text), train_small["labels"])

language_pred = language_model.predict(test_df["text"].map(clean_text))
print("Language accuracy:", accuracy_score(test_df["labels"], language_pred))
print("Language macro F1:", f1_score(test_df["labels"], language_pred, average="macro"))
print(classification_report(test_df["labels"], language_pred, zero_division=0))


def detect_language(message):
    text = clean_text(message)
    if not text:
        return {
            "language": "unknown",
            "confidence": 0.0,
            "supported_language": False,
            "status": "empty"
        }
    probabilities = language_model.predict_proba([text])[0]
    index = int(np.argmax(probabilities))
    language = language_model.classes_[index]
    confidence = float(probabilities[index])
    return {
        "language": language,
        "confidence": round(confidence, 4),
        "supported_language": language in {"en", "ar"},
        "status": "ok" if confidence >= 0.55 else "low_confidence"
    }

print(detect_language("Where is my order?"))
print(detect_language("أين طلبي؟"))

DatasetDict({
    train: Dataset({
        features: ['labels', 'text'],
        num_rows: 70000
    })
    validation: Dataset({
        features: ['labels', 'text'],
        num_rows: 10000
    })
    test: Dataset({
        features: ['labels', 'text'],
        num_rows: 10000
    })
})
['labels', 'text']
{'labels': 'pt', 'text': 'os chefes de defesa da estónia, letónia, lituânia, alemanha, itália, espanha e eslováquia assinarão o acordo para fornecer pessoal e financiamento para o centro.'}

/tmp/ipykernel_1885/2355414700.py:14: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda group: group.sample(n=min(SAMPLES_PER_LANGUAGE, len(group)), random_state=SEED))

Language accuracy: 0.9903
Language macro F1: 0.9903813762328373
              precision    recall  f1-score   support

          ar       1.00      0.98      0.99       500
          bg       0.99      0.99      0.99       500
          de       1.00      1.00      1.00       500
          el       1.00      1.00      1.00       500
          en       1.00      1.00      1.00       500
          es       0.99      1.00      0.99       500
          fr       1.00      1.00      1.00       500
          hi       1.00      0.95      0.98       500
          it       0.99      0.99      0.99       500
          ja       1.00      0.99      0.99       500
          nl       1.00      0.99      0.99       500
          pl       1.00      1.00      1.00       500
          pt       1.00      0.99      0.99       500
          ru       1.00      0.99      1.00       500
          sw       0.96      0.99      0.97       500
          th       1.00      0.98      0.99       500
          tr       0.99      1.00      0.99       500
          ur       1.00      0.96      0.98       500
          vi       1.00      1.00      1.00       500
          zh       0.91      1.00      0.95       500

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000

{'language': 'en', 'confidence': 0.2708, 'supported_language': True, 'status': 'low_confidence'}
{'language': 'zh', 'confidence': 0.157, 'supported_language': False, 'status': 'low_confidence'}

## **Module 2: emotion classification**

In [38]:
# Pretrained baseline; this avoids fine-tuning time during the one-hour deadline.
# The model is based on the six labels from dair-ai/emotion.
emotion_model = pipeline(
    "text-classification",
    model="j-hartmann/emotion-english-distilroberta-base",
    top_k=1,
    device=-1,
)

EMOTION_TO_BUCKET = {
    "anger": "negative_frustrated",
    "sadness": "negative_frustrated",
    "fear": "negative_frustrated",
    "joy": "positive_satisfied",
    "love": "positive_satisfied",
    "surprise": "neutral_or_uncertain",
    "neutral": "neutral_or_uncertain",
}


def classify_emotion(message):
    text = clean_text(message)
    if not text:
        return {
            "emotion": "unknown",
            "sentiment_bucket": "neutral_or_uncertain",
            "confidence": 0.0
        }

    output = emotion_model(text)[0]
    if isinstance(output, list):
        output = output[0]
    emotion = output["label"].lower()
    return {
        "emotion": emotion,
        "sentiment_bucket": EMOTION_TO_BUCKET.get(emotion, "neutral_or_uncertain"),
        "confidence": round(float(output["score"]), 4)
    }

for example in [
    "I am furious because my payment failed again.",
    "Thank you, the delivery was great!",
    "I am worried that my refund has not arrived."
]:
    print(example, "->", classify_emotion(example))

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

I am furious because my payment failed again. -> {'emotion': 'anger', 'sentiment_bucket': 'negative_frustrated', 'confidence': 0.9895}
Thank you, the delivery was great! -> {'emotion': 'joy', 'sentiment_bucket': 'positive_satisfied', 'confidence': 0.9442}
I am worried that my refund has not arrived. -> {'emotion': 'fear', 'sentiment_bucket': 'negative_frustrated', 'confidence': 0.9295}

### Emotion-model limitation

The required `dair-ai/emotion` dataset contains English Twitter messages with six classes: sadness, joy, love, anger, fear, and surprise. Because of the short deadline, this prototype uses a pretrained English emotion classifier rather than fine-tuning during this run. The routing bucket is derived transparently: anger/sadness/fear are negative-frustrated, joy/love are positive-satisfied, and surprise is neutral-or-uncertain. This is a limitation because Twitter emotion data may not transfer perfectly to e-commerce customer-support language.

## **Module 3: Bitext intent classification**

In [39]:
bitext_ds = load_dataset("bitext/Bitext-customer-support-llm-chatbot-training-dataset", split="train")
bitext_df = bitext_ds.to_pandas()

print("Columns:", bitext_df.columns.tolist())
print("Rows:", len(bitext_df))
print(bitext_df.head())
print(bitext_df["intent"].value_counts())

# Sample 250 examples per intent to finish on time.
INTENT_SAMPLES_PER_CLASS = 250
intent_train_df = (
    bitext_df.groupby("intent", group_keys=False)
    .apply(lambda group: group.sample(n=min(INTENT_SAMPLES_PER_CLASS, len(group)), random_state=SEED))
    .sample(frac=1, random_state=SEED)
    .reset_index(drop=True)
)

# Stratified 80/20 evaluation split. This is separate from the RAG holdout later.
from sklearn.model_selection import train_test_split

X_train_intent, X_test_intent, y_train_intent, y_test_intent = train_test_split(
    intent_train_df["instruction"].map(clean_text),
    intent_train_df["intent"],
    test_size=0.20,
    random_state=SEED,
    stratify=intent_train_df["intent"],
)

intent_model = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=1, sublinear_tf=True)),
    ("clf", LogisticRegression(max_iter=500, n_jobs=-1, random_state=SEED))
])
intent_model.fit(X_train_intent, y_train_intent)

intent_pred = intent_model.predict(X_test_intent)
print("Intent accuracy:", accuracy_score(y_test_intent, intent_pred))
print("Intent macro F1:", f1_score(y_test_intent, intent_pred, average="macro"))
print(classification_report(y_test_intent, intent_pred, zero_division=0))

INTENT_TO_ROUTE = {
    "track_order": "order_status",
    "delivery_period": "order_status",
    "delivery_options": "order_status",
    "cancel_order": "order_management",
    "change_order": "order_management",
    "place_order": "order_management",
    "change_shipping_address": "order_management",
    "set_up_shipping_address": "order_management",
    "check_invoice": "billing_and_refunds",
    "get_invoice": "billing_and_refunds",
    "check_payment_methods": "billing_and_refunds",
    "payment_issue": "billing_and_refunds",
    "check_cancellation_fee": "billing_and_refunds",
    "check_refund_policy": "billing_and_refunds",
    "get_refund": "billing_and_refunds",
    "track_refund": "billing_and_refunds",
    "create_account": "account_management",
    "delete_account": "account_management",
    "edit_account": "account_management",
    "switch_account": "account_management",
    "recover_password": "account_management",
    "registration_problems": "account_management",
    "newsletter_subscription": "account_management",
    "complaint": "complaint",
    "review": "complaint",
    "contact_customer_service": "complaint",
    "contact_human_agent": "complaint",
}


def classify_intent(message):
    text = clean_text(message)
    probabilities = intent_model.predict_proba([text])[0]
    index = int(np.argmax(probabilities))
    intent = intent_model.classes_[index]
    return {
        "intent": intent,
        "routing_group": INTENT_TO_ROUTE.get(intent, "out_of_scope"),
        "confidence": round(float(probabilities[index]), 4)
    }

print(classify_intent("I want to know where my order is"))
print(classify_intent("My payment did not go through"))

Columns: ['flags', 'instruction', 'category', 'intent', 'response']
Rows: 26872
   flags                                        instruction category  \
0      B   question about cancelling order {{Order Number}}    ORDER
1    BQZ  i have a question about cancelling oorder {{Or...    ORDER
2   BLQZ    i need help cancelling puchase {{Order Number}}    ORDER
3     BL         I need to cancel purchase {{Order Number}}    ORDER
4  BCELN  I cannot afford this order, cancel purchase {{...    ORDER

         intent                                           response
0  cancel_order  I've understood you have a question regarding ...
1  cancel_order  I've been informed that you have a question ab...
2  cancel_order  I can sense that you're seeking assistance wit...
3  cancel_order  I understood that you need assistance with can...
4  cancel_order  I'm sensitive to the fact that you're facing f...
intent
contact_customer_service    1000
complaint                   1000
check_invoice               1000
switch_account              1000
edit_account                1000
contact_human_agent          999
check_payment_methods        999
delivery_period              999
newsletter_subscription      999
get_invoice                  999
payment_issue                999
registration_problems        999
cancel_order                 998
place_order                  998
track_refund                 998
change_order                 997
set_up_shipping_address      997
check_refund_policy          997
create_account               997
get_refund                   997
review                       997
delivery_options             995
delete_account               995
recover_password             995
track_order                  995
change_shipping_address      973
check_cancellation_fee       950
Name: count, dtype: int64

/tmp/ipykernel_1885/4062436805.py:13: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda group: group.sample(n=min(INTENT_SAMPLES_PER_CLASS, len(group)), random_state=SEED))

Intent accuracy: 0.977037037037037
Intent macro F1: 0.9773443522566642
                          precision    recall  f1-score   support

            cancel_order       1.00      0.88      0.94        50
            change_order       0.80      0.98      0.88        50
 change_shipping_address       1.00      0.98      0.99        50
  check_cancellation_fee       0.98      1.00      0.99        50
           check_invoice       0.98      0.98      0.98        50
   check_payment_methods       1.00      1.00      1.00        50
     check_refund_policy       1.00      0.98      0.99        50
               complaint       1.00      1.00      1.00        50
contact_customer_service       1.00      0.98      0.99        50
     contact_human_agent       0.98      1.00      0.99        50
          create_account       0.96      0.98      0.97        50
          delete_account       0.86      1.00      0.93        50
        delivery_options       0.98      1.00      0.99        50
         delivery_period       1.00      1.00      1.00        50
            edit_account       1.00      0.88      0.94        50
             get_invoice       0.98      0.98      0.98        50
              get_refund       1.00      0.98      0.99        50
 newsletter_subscription       1.00      1.00      1.00        50
           payment_issue       1.00      0.98      0.99        50
             place_order       0.96      0.96      0.96        50
        recover_password       1.00      1.00      1.00        50
   registration_problems       0.98      0.98      0.98        50
                  review       1.00      1.00      1.00        50
 set_up_shipping_address       1.00      1.00      1.00        50
          switch_account       1.00      0.96      0.98        50
             track_order       1.00      0.90      0.95        50
            track_refund       0.98      1.00      0.99        50

                accuracy                           0.98      1350
               macro avg       0.98      0.98      0.98      1350
            weighted avg       0.98      0.98      0.98      1350

{'intent': 'delivery_period', 'routing_group': 'order_status', 'confidence': 0.1091}
{'intent': 'payment_issue', 'routing_group': 'billing_and_refunds', 'confidence': 0.1407}

## **Module 4: lightweight RAG**

In [40]:
# Keep a RAG holdout out of the index, so you can evaluate retrieval honestly.
rag_source_df = bitext_df.drop_duplicates(subset=["instruction", "response"]).copy()

rag_holdout = (
    rag_source_df.groupby("intent", group_keys=False)
    .apply(lambda group: group.sample(n=min(20, len(group)), random_state=SEED))
    .copy()
)

rag_kb_df = rag_source_df.drop(index=rag_holdout.index).reset_index(drop=True)
rag_holdout = rag_holdout.reset_index(drop=True)

print("Knowledge-base rows:", len(rag_kb_df))
print("Retrieval holdout rows:", len(rag_holdout))

embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

# Embed instructions only: the user query is semantically closest to support questions.
kb_embeddings = embedding_model.encode(
    rag_kb_df["instruction"].tolist(),
    normalize_embeddings=True,
    show_progress_bar=True,
).astype("float32")

faiss_index = faiss.IndexFlatIP(kb_embeddings.shape[1])
faiss_index.add(kb_embeddings)
print("FAISS vectors:", faiss_index.ntotal)


def retrieve_support_context(query, predicted_intent=None, top_k=3, threshold=0.35):
    query_embedding = embedding_model.encode(
        [clean_text(query)], normalize_embeddings=True
    ).astype("float32")
    scores, indices = faiss_index.search(query_embedding, top_k * 3)

    candidates = rag_kb_df.iloc[indices[0]].copy()
    candidates["similarity"] = scores[0]

    # Prefer matching intent, but do not force a hard filter that could hide a useful record.
    if predicted_intent is not None:
        candidates["intent_match"] = candidates["intent"].eq(predicted_intent)
        candidates = candidates.sort_values(
            ["intent_match", "similarity"], ascending=[False, False]
        )
    else:
        candidates = candidates.sort_values("similarity", ascending=False)

    candidates = candidates[candidates["similarity"] >= threshold].head(top_k)
    return candidates[["instruction", "response", "intent", "category", "similarity"]].to_dict("records")


def build_grounded_response(message, language, emotion_result, intent_result, retrieved_docs):
    if not retrieved_docs:
        if language == "ar":
            return "لا أملك معلومات دعم كافية للإجابة بدقة. يرجى التواصل مع فريق الدعم البشري للحصول على المساعدة."
        return "I do not have enough verified support information to answer that accurately. Please contact a human support agent for help."

    best = retrieved_docs[0]
    base_answer = best["response"]

    # It is an extractive fallback, not a claim of completing any action.
    if emotion_result["sentiment_bucket"] == "negative_frustrated":
        if language == "ar":
            return "أتفهم أن هذا الأمر محبط. بناءً على معلومات الدعم المتاحة: " + base_answer
        return "I understand this is frustrating. Based on the available support information: " + base_answer

    if language == "ar":
        return "بناءً على معلومات الدعم المتاحة: " + base_answer
    return "Based on the available support information: " + base_answer

/tmp/ipykernel_1885/3867878132.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda group: group.sample(n=min(20, len(group)), random_state=SEED))

Knowledge-base rows: 26332
Retrieval holdout rows: 540

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/823 [00:00<?, ?it/s]

FAISS vectors: 26332

## **End-to-end integrated pipeline**

In [41]:
GREETINGS = {"hi", "hello", "hey", "good morning", "good evening", "مرحبا", "السلام عليكم", "اهلا"}
GOODBYES = {"bye", "goodbye", "see you", "مع السلامة", "وداعا"}
THANKS = {"thanks", "thank you", "thx", "شكرا", "شكراً"}


def direct_social_response(message, language):
    text = clean_text(message).lower()
    if text in GREETINGS:
        return "مرحباً! كيف يمكنني مساعدتك؟" if language == "ar" else "Hello! How can I help you today?"
    if text in GOODBYES:
        return "مع السلامة، وأتمنى لك يوماً سعيداً." if language == "ar" else "Goodbye, and have a great day."
    if text in THANKS:
        return "على الرحب والسعة!" if language == "ar" else "You are welcome!"
    return None


def process_customer_message(user_message):
    text = clean_text(user_message)
    language_result = detect_language(text)

    if language_result["status"] == "empty":
        return {
            "response": "Please enter a customer-support question.",
            **language_result,
            "emotion": "unknown",
            "sentiment_bucket": "neutral_or_uncertain",
            "intent": "out_of_scope",
            "routing_group": "out_of_scope",
            "requires_escalation": False,
            "priority": "normal",
            "retrieved_documents": 0,
            "generation_mode": "safe_template",
        }

    language = language_result["language"]
    if not language_result["supported_language"]:
        return {
            "response": "Sorry, this prototype currently supports customer-support responses in English and Arabic.",
            **language_result,
            "emotion": "unknown",
            "sentiment_bucket": "neutral_or_uncertain",
            "intent": "out_of_scope",
            "routing_group": "out_of_scope",
            "requires_escalation": False,
            "priority": "normal",
            "retrieved_documents": 0,
            "generation_mode": "safe_template",
        }

    social_response = direct_social_response(text, language)
    if social_response is not None:
        return {
            "response": social_response,
            **language_result,
            "emotion": "unknown",
            "sentiment_bucket": "neutral_or_uncertain",
            "intent": "social",
            "routing_group": "greeting_goodbye_gratitude",
            "requires_escalation": False,
            "priority": "normal",
            "retrieved_documents": 0,
            "generation_mode": "direct_template",
        }

    # This one-hour prototype is evaluated primarily in English.
    # Arabic emotion/intent/RAG behavior must be reported as a limitation unless translation is added and tested.
    if language == "ar":
        return {
            "response": "أستطيع التعرف على أن رسالتك بالعربية، لكن التحليل الكامل للاسترجاع في هذا النموذج الأولي تم تقييمه باللغة الإنجليزية فقط. يرجى التواصل مع الدعم البشري للحصول على مساعدة دقيقة.",
            **language_result,
            "emotion": "unknown",
            "sentiment_bucket": "neutral_or_uncertain",
            "intent": "out_of_scope",
            "routing_group": "out_of_scope",
            "requires_escalation": True,
            "priority": "normal",
            "retrieved_documents": 0,
            "generation_mode": "safe_template",
        }

    emotion_result = classify_emotion(text)
    intent_result = classify_intent(text)

    complaint_intents = {"complaint", "contact_customer_service", "contact_human_agent"}
    requires_escalation = intent_result["intent"] in complaint_intents
    priority = "high" if requires_escalation and emotion_result["sentiment_bucket"] == "negative_frustrated" else "normal"

    retrieved_docs = retrieve_support_context(
        text,
        predicted_intent=intent_result["intent"],
        top_k=3,
        threshold=0.35,
    )

    response = build_grounded_response(
        message=text,
        language=language,
        emotion_result=emotion_result,
        intent_result=intent_result,
        retrieved_docs=retrieved_docs,
    )

    return {
        "response": response,
        **language_result,
        **emotion_result,
        **intent_result,
        "requires_escalation": requires_escalation,
        "priority": priority,
        "retrieved_documents": len(retrieved_docs),
        "generation_mode": "extractive_grounded_fallback",
    }

## **End-to-end test cases**

In [42]:
TEST_MESSAGES = [
    "Hello",
    "Where is my order?",
    "My payment failed and I am really angry.",
    "I want to complain about your terrible service.",
    "Thank you for your help!",
    "What is the capital of France?",
    "أين طلبي؟",
    "Bonjour, où est ma commande ?",
    "   ",
]

results = []
for message in TEST_MESSAGES:
    result = process_customer_message(message)
    results.append({"message": message, **result})

results_df = pd.DataFrame(results)
display(results_df)

,message,response,language,confidence,supported_language,status,emotion,sentiment_bucket,intent,routing_group,requires_escalation,priority,retrieved_documents,generation_mode
0,Hello,"Sorry, this prototype currently supports custo...",zh,0.1326,False,low_confidence,unknown,neutral_or_uncertain,out_of_scope,out_of_scope,False,normal,0,safe_template
1,Where is my order?,Based on the available support information: We...,en,0.0873,True,low_confidence,neutral,neutral_or_uncertain,delivery_period,order_status,False,normal,3,extractive_grounded_fallback
2,My payment failed and I am really angry.,I understand this is frustrating. Based on the...,en,0.2221,True,low_confidence,anger,negative_frustrated,payment_issue,billing_and_refunds,False,normal,3,extractive_grounded_fallback
3,I want to complain about your terrible service.,I understand this is frustrating. Based on the...,en,0.4610,True,low_confidence,fear,negative_frustrated,review,complaint,False,normal,3,extractive_grounded_fallback
4,Thank you for your help!,I do not have enough verified support informat...,en,0.3936,True,low_confidence,joy,positive_satisfied,review,complaint,False,normal,0,extractive_grounded_fallback
5,What is the capital of France?,I do not have enough verified support informat...,en,0.0942,True,low_confidence,neutral,neutral_or_uncertain,check_cancellation_fee,billing_and_refunds,False,normal,0,extractive_grounded_fallback
6,أين طلبي؟,"Sorry, this prototype currently supports custo...",zh,0.1570,False,low_confidence,unknown,neutral_or_uncertain,out_of_scope,out_of_scope,False,normal,0,safe_template
7,"Bonjour, où est ma commande ?","Sorry, this prototype currently supports custo...",fr,0.3298,False,low_confidence,unknown,neutral_or_uncertain,out_of_scope,out_of_scope,False,normal,0,safe_template
8,,Please enter a customer-support question.,unknown,0.0000,False,empty,unknown,neutral_or_uncertain,out_of_scope,out_of_scope,False,normal,0,safe_template

## **Fast RAG retrieval evaluation**

In [43]:
EVAL_N = min(100, len(rag_holdout))
retrieval_results = []

for _, row in rag_holdout.sample(EVAL_N, random_state=SEED).iterrows():
    docs = retrieve_support_context(row["instruction"], predicted_intent=None, top_k=3, threshold=-1.0)
    retrieved_intents = [doc["intent"] for doc in docs]
    retrieval_results.append({
        "query": row["instruction"],
        "true_intent": row["intent"],
        "top_3_intents": retrieved_intents,
        "hit_at_1": int(len(retrieved_intents) > 0 and retrieved_intents[0] == row["intent"]),
        "hit_at_3": int(row["intent"] in retrieved_intents),
    })

retrieval_eval_df = pd.DataFrame(retrieval_results)
print("Retrieval Hit@1:", retrieval_eval_df["hit_at_1"].mean())
print("Retrieval Hit@3:", retrieval_eval_df["hit_at_3"].mean())
display(retrieval_eval_df.head(10))

Retrieval Hit@1: 0.99
Retrieval Hit@3: 1.0

,query,true_intent,top_3_intents,hit_at_1,hit_at_3
0,remove platinum account,delete_account,"[delete_account, delete_account, delete_account]",1,1
1,where could I check the goddamn cancellation c...,check_cancellation_fee,"[check_cancellation_fee, check_cancellation_fe...",1,1
2,I am waiting for a restitution of {{Currency S...,track_refund,"[track_refund, track_refund, track_refund]",1,1
3,I can't locate my invoices from {{Person Name}},check_invoice,"[check_invoice, check_invoice, check_invoice]",1,1
4,can you help me setting another delivery addrs...,set_up_shipping_address,"[set_up_shipping_address, change_shipping_addr...",1,1
5,seeing withdrawal penalty,check_cancellation_fee,"[check_cancellation_fee, check_cancellation_fe...",1,1
6,i want help to change the info on my user,edit_account,"[edit_account, edit_account, edit_account]",1,1
7,can you help me to retrieve my user profile key?,recover_password,"[recover_password, recover_password, recover_p...",1,1
8,can uhelp me subscribe to ur newsletter,newsletter_subscription,"[newsletter_subscription, newsletter_subscript...",1,1
9,need assistance purchasing some of ur article,place_order,"[place_order, place_order, place_order]",1,1